const PRESENTATION_META = {
 student: "Atila Fazrul Falah",
 nim: "00000111118",
 totalSlides: 17,
};

const SLIDES = [
 {
 id: 1,
 title: "Latar Belakang Masalah",
 subtitle: "Kebutuhan Sistem Terintegrasi untuk Monitoring Pekerjaan & Inventaris Aset",
 category: "pembuka",
 categoryLabel: "Pendahuluan",
 notes:
 "Selamat pagi/siang Bapak/Ibu penguji dan Bapak/Ibu dosen pembimbing. Pada slide ini saya memaparkan latar belakang masalah di PT. Hayati Semesta Raharja. Seiring bertambahnya volume pekerjaan dan aset operasional, proses monitoring dan inventaris yang masih manual berpotensi menimbulkan kesalahan pencatatan serta keterlambatan informasi antar divisi.",
 points: [
 { title: "Kondisi awal di perusahaan", desc: "PT. HSR masih mengandalkan pencatatan manual atau semi-digital untuk monitoring pekerjaan dan inventaris aset." },
 { title: "Dampak operasional", desc: "Berpotensi menimbulkan kesalahan pencatatan, keterlambatan informasi, dan kesulitan pengawasan lintas divisi." },
 { title: "Kebutuhan solusi", desc: "Dibutuhkan sistem berbasis web yang mengintegrasikan monitoring pekerjaan dan pengelolaan inventaris dalam satu platform." },
 { title: "Solusi yang dikembangkan", desc: "MANSYS (Management System) dirancang sebagai platform terpusat untuk menjawab kebutuhan tersebut." },
 ],
 },
 {
 id: 2,
 title: "Maksud dan Tujuan Kerja Magang",
 subtitle: "Pemenuhan Akademik & Pengembangan Sistem Digital Operasional",
 category: "profil",
 categoryLabel: "Pendahuluan",
 notes:
 "Magang dilaksanakan sebagai pemenuhan kewajiban akademik sekaligus pengalaman kerja profesional. Tujuan utamanya adalah merancang dan membangun MANSYS menggunakan React.js, Laravel REST API, dan MySQL agar operasional perusahaan lebih efisien dan terintegrasi.",
 points: [
 { title: "Maksud magang", desc: "Menerapkan ilmu perkuliahan ke lingkungan kerja nyata serta meningkatkan kemampuan teknis dan kolaborasi tim." },
 { title: "Tujuan utama", desc: "Merancang dan mengembangkan sistem monitoring pekerjaan serta inventaris aset yang terpusat di PT. HSR." },
 { title: "Tujuan teknis", desc: "Implementasi React.js (frontend), Laravel REST API (backend), dan MySQL (database) dengan autentikasi Laravel Sanctum." },
 { title: "Target hasil", desc: "Operasional lebih efektif, transparan, dan minim risiko kesalahan pencatatan data." },
 ],
 },
 {
 id: 3,
 title: "Sejarah Singkat Perusahaan",
 subtitle: "Visi, Misi, dan Struktur Organisasi PT. Hayati Semesta Raharja",
 category: "profil",
 categoryLabel: "Gambaran Umum Perusahaan",
 notes:
 "PT. Hayati Semesta Raharja adalah perusahaan domestik di sektor kesehatan. Persiapan usaha dimulai sejak 2017 dan resmi berbadan hukum pada 2021. Perusahaan bergerak di perdagangan alat medis, farmasi, laboratorium, radiologi, serta layanan servis perangkat kesehatan.",
 points: [
 { title: "Profil perusahaan", desc: "PT. HSR berdiri sejak persiapan 2017, resmi badan hukum 2021, dipimpin Direktur Utama Syahrul Roji." },
 { title: "Ruang lingkup bisnis", desc: "Distribusi alat kesehatan, BHP, servis hardware/software perangkat medis, dan konstruksi ruang medis." },
 { title: "Visi", desc: "Menjadi perusahaan yang bermanfaat dalam perkembangan fasilitas kesehatan di Indonesia." },
 { title: "Misi", desc: "Membangun perusahaan yang berdedikasi dan terdepan dalam industri kesehatan Indonesia." },
 ],
 },
 {
 id: 4,
 title: "Uraian Pelaksanaan Magang",
 subtitle: "Posisi, Koordinasi, dan Alur Kerja Pengembangan MANSYS",
 category: "fitur",
 categoryLabel: "Pelaksanaan Kerja Magang",
 notes:
 "Selama 6 bulan (Februari-Juli 2026), saya ditempatkan di departemen IT sebagai Software Developer Intern. Koordinasi dilakukan dengan Direktur IT, Direktur Utama, tim intern, serta divisi operasional untuk memetakan kebutuhan sistem yang sesuai alur kerja perusahaan.",
 points: [
 { title: "Posisi & periode", desc: "Software Developer Intern di departemen IT, WFO di kantor pusat Tangerang, durasi 6 bulan." },
 { title: "Koordinasi internal", desc: "Berkolaborasi dengan 2 intern lain dalam pengembangan sistem, dengan pelaporan progres mingguan." },
 { title: "Koordinasi lintas divisi", desc: "Berinteraksi dengan Sales, Service, Kontraktor, Logistik, dan Purchasing untuk pemetaan kebutuhan." },
 { title: "Metodologi pengembangan", desc: "Perencanaan bertahap, pengembangan iteratif, integrasi REST API, dan pengujian fungsional berkala." },
 ],
 },
 {
 id: 5,
 title: "Uraian Sistem MANSYS",
 subtitle: "Arsitektur, Role-Based Access, dan Modul Utama",
 category: "fitur",
 categoryLabel: "Pelaksanaan Kerja Magang",
 notes:
 "MANSYS dibangun dengan arsitektur decoupled: React.js sebagai SPA frontend dan Laravel sebagai REST API backend. Sistem menerapkan role-based access control dengan tiga level: Super Admin, Admin, dan User, serta pembagian modul per divisi operasional.",
 points: [
 { title: "Arsitektur teknologi", desc: "React.js (SPA) + Laravel REST API + MySQL, dengan autentikasi token Laravel Sanctum." },
 { title: "Role pengguna", desc: "Super Admin (akses penuh), Admin (operasional per divisi), User (monitoring terbatas)." },
 { title: "5 modul utama", desc: "(1) Dashboard, (2) Projek Kerja, (3) Manajemen Karyawan, (4) Manajemen Inventory, (5) Pengajuan & Approval Cuti." },
 { title: "Alur status pekerjaan", desc: "Projek: Dibuat → Persiapan → Proses → Editing → Invoicing → Selesai. Pembelian: Dipesan → Dikirim → Diterima." },
 ],
 },
 {
 id: 6,
 title: "Use Case Diagram MANSYS",
 subtitle: "Interaksi Aktor Divisi dengan Modul Utama Sistem",
 category: "fitur",
 categoryLabel: "Gambaran Sistem",
 notes:
 "Use case diagram menggambarkan interaksi Sales, Service, dan Purchasing dengan modul projek, inventory, target, dan pembelian. Diagram ini selaras dengan implementasi di web-HSR dan menjadi acuan pembagian modul per divisi.",
 flowchart: true,
 flowchartFull: true,
 usecase: true,
 image: "assets/flow-usecase-mansys.png",
 imageCaption: "Use case diagram MANSYS — interaksi aktor divisi dengan modul utama",
 },
 {
 id: 7,
 title: "Flowchart Autentikasi & Role-Based Access",
 subtitle: "Alur Login, Laravel Sanctum, dan Routing Berdasarkan Role",
 category: "fitur",
 categoryLabel: "Flowchart Sistem",
 notes:
 "Flowchart autentikasi: pengguna login via POST /api/login, token Sanctum disimpan, lalu diarahkan ke dashboard sesuai role super_admin, admin, atau user. Sistem memantau idle 15 menit dan session timeout.",
 flowchart: true,
 flowchartFull: true,
 image: "assets/flow-auth-role.png",
 imageCaption: "Flowchart autentikasi & role-based access (idle 15 menit memicu session timeout → login ulang)",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Mulai", r: 0, c: 1 },
 { id: "open", type: "process", text: "Buka Aplikasi MANSYS", r: 1, c: 1 },
 { id: "token", type: "decision", text: "Token Sanctum valid?", r: 2, c: 1 },
 { id: "login", type: "process", text: "Tampilkan halaman login", r: 3, c: 1 },
 { id: "post", type: "io", text: "Input kredensial → POST /api/login", r: 4, c: 1 },
 { id: "loginok", type: "decision", text: "Login berhasil?", r: 5, c: 1 },
 { id: "savetoken", type: "process", text: "Simpan token Sanctum", r: 6, c: 1 },
 { id: "role", type: "decision", text: "Cek user.role", r: 7, c: 1 },
 { id: "sa", type: "process", text: "Route /super-admin/*", r: 8, c: 0 },
 { id: "adm", type: "process", text: "Route /admin/*", r: 8, c: 1 },
 { id: "usr", type: "process", text: "Route /user/*", r: 8, c: 2 },
 { id: "dash", type: "end", text: "Dashboard sesuai role", r: 9, c: 1 },
 ],
 edges: [
 { from: "start", to: "open" },
 { from: "open", to: "token" },
 { from: "token", to: "login", label: "Tidak" },
 { from: "token", to: "role", label: "Ya", lane: "right" },
 { from: "login", to: "post" },
 { from: "post", to: "loginok" },
 { from: "loginok", to: "login", label: "Tidak", lane: "left" },
 { from: "loginok", to: "savetoken", label: "Ya" },
 { from: "savetoken", to: "role" },
 { from: "role", to: "sa", label: "super_admin" },
 { from: "role", to: "adm", label: "admin" },
 { from: "role", to: "usr", label: "user" },
 { from: "sa", to: "dash" },
 { from: "adm", to: "dash" },
 { from: "usr", to: "dash" },
 ],
 },
 },
 {
 id: 8,
 title: "Flowchart Navigasi Modul MANSYS",
 subtitle: "Sidebar, Division Hub, dan Integrasi REST API",
 category: "fitur",
 categoryLabel: "Flowchart Sistem",
 notes:
 "Setelah login, pengguna mengakses modul global via sidebar atau modul divisi via division hub. Semua halaman React.js terhubung ke REST API Laravel.",
 flowchart: true,
 flowchartFull: true,
 image: "assets/flow-module-nav.png",
 imageCaption: "Flowchart navigasi modul MANSYS",
 flow: {
 cols: 3,
 nodes: [
 { id: "dash", type: "start", text: "Dashboard (setelah login)", r: 0, c: 1 },
 { id: "pick", type: "decision", text: "Pilih jenis menu?", r: 1, c: 1 },
 { id: "gnav", type: "process", text: "Sidebar — Menu Global", r: 2, c: 0 },
 { id: "dnav", type: "process", text: "Division Hub — pilih divisi", r: 2, c: 2 },
 { id: "gpage", type: "process", text: "Karyawan, Cuti, Rekap Biaya, Berita Acara", r: 3, c: 0 },
 { id: "dpage", type: "process", text: "Projek, Inventory, Pembelian, Target, Daily Report", r: 3, c: 2 },
 { id: "react", type: "process", text: "Halaman React.js (komponen page)", r: 4, c: 1 },
 { id: "api", type: "io", text: "Request REST API Laravel (token Sanctum)", r: 5, c: 1 },
 { id: "render", type: "end", text: "Render data sesuai hak akses", r: 6, c: 1 },
 ],
 edges: [
 { from: "dash", to: "pick" },
 { from: "pick", to: "gnav", label: "Modul Global" },
 { from: "pick", to: "dnav", label: "Modul Divisi" },
 { from: "gnav", to: "gpage" },
 { from: "dnav", to: "dpage" },
 { from: "gpage", to: "react" },
 { from: "dpage", to: "react" },
 { from: "react", to: "api" },
 { from: "api", to: "render" },
 ],
 },
 },
 {
 id: 9,
 title: "5 Modul yang Diimplementasikan",
 subtitle: "Dashboard, Projek Kerja, Karyawan, Inventory, dan Cuti Karyawan",
 category: "fitur",
 categoryLabel: "Implementasi Fitur",
 notes:
 "Selama 15 minggu pengembangan, penulis mengimplementasikan 5 modul utama. Slide berikutnya menampilkan flowchart alur kerja dan screenshot implementasi tiap modul.",
 points: [
 { title: "1. Dashboard Super Admin & Admin", desc: "Halaman utama setelah login, ringkasan pekerjaan per divisi sesuai role." },
 { title: "2. Modul Projek Kerja", desc: "CRUD projek, status pekerjaan, invite user, upload dokumentasi foto/file." },
 { title: "3. Modul Manajemen Karyawan", desc: "Pendataan identitas, divisi, role, dan dokumen pendukung karyawan." },
 { title: "4. Modul Manajemen Inventory", desc: "Pendataan aset per divisi: kode barang, stok, lokasi, kategori, foto." },
 { title: "5. Modul Pengajuan & Approval Cuti", desc: "Pengajuan cuti Admin dan approval Super Admin (pending/approved/rejected)." },
 ],
 },
 {
 id: 10,
 title: "Implementasi Modul 1: Dashboard",
 subtitle: "Flowchart Alur & Tampilan Dashboard Super Admin dan Admin",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul dashboard menampilkan card per divisi beserta jumlah pekerjaan. Super Admin melihat seluruh divisi, Admin hanya divisi masing-masing. Data diambil via GET /projek-kerja dengan filter role.",
 flowchart: "assets/flow-mod-dashboard.png",
 flowchartCaption: "Flowchart alur modul Dashboard",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Mulai", r: 0, c: 1 },
 { id: "login", type: "process", text: "Login (token Sanctum)", r: 1, c: 1 },
 { id: "role", type: "decision", text: "Cek role user?", r: 2, c: 1 },
 { id: "sa", type: "process", text: "Super Admin: semua divisi", r: 3, c: 0 },
 { id: "adm", type: "process", text: "Admin: divisi sendiri", r: 3, c: 1 },
 { id: "usr", type: "process", text: "User: projek di-invite", r: 3, c: 2 },
 { id: "get", type: "io", text: "GET /projek-kerja (filter role)", r: 4, c: 1 },
 { id: "count", type: "process", text: "Hitung jumlah pekerjaan / divisi", r: 5, c: 1 },
 { id: "render", type: "end", text: "Render DivisiCard", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "login" },
 { from: "login", to: "role" },
 { from: "role", to: "sa", label: "super_admin" },
 { from: "role", to: "adm", label: "admin" },
 { from: "role", to: "usr", label: "user" },
 { from: "sa", to: "get" },
 { from: "adm", to: "get" },
 { from: "usr", to: "get" },
 { from: "get", to: "count" },
 { from: "count", to: "render" },
 ],
 },
 images: [
 { src: "assets/screen-dashboard-sa.png", label: "Dashboard Super Admin" },
 { src: "assets/screen-dashboard-admin.png", label: "Dashboard Admin" },
 ],
 imageCaption: "Gambar 3.1–3.2: Tampilan dashboard Super Admin dan Admin",
 },
 {
 id: 11,
 title: "Implementasi Modul 2: Projek Kerja",
 subtitle: "Flowchart Alur & Tampilan Form dan Tabel Projek",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul projek kerja mendukung penambahan projek, pengisian divisi, karyawan, lokasi, status, upload dokumentasi, serta tabel data dengan pencarian dan aksi CRUD.",
 flowchart: "assets/flow-mod-projek.png",
 flowchartCaption: "Flowchart alur modul Projek Kerja",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka Projek Kerja", r: 0, c: 1 },
 { id: "form", type: "process", text: "Form Tambah Projek (divisi, lokasi, karyawan)", r: 1, c: 1 },
 { id: "valid", type: "decision", text: "Input valid?", r: 2, c: 1 },
 { id: "err", type: "process", text: "Tampilkan pesan error", r: 3, c: 2 },
 { id: "upload", type: "process", text: "Upload foto & dokumen", r: 3, c: 1 },
 { id: "post", type: "io", text: "POST /projek-kerja", r: 4, c: 1 },
 { id: "status", type: "process", text: "Set status awal: Dibuat", r: 5, c: 1 },
 { id: "patch", type: "io", text: "PATCH status: Persiapan → Proses → Editing → Invoicing → Selesai", r: 6, c: 1 },
 { id: "table", type: "end", text: "Tampil tabel data projek", r: 7, c: 1 },
 ],
 edges: [
 { from: "start", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "upload", label: "Ya" },
 { from: "valid", to: "err", label: "Tidak" },
 { from: "err", to: "form", lane: "right" },
 { from: "upload", to: "post" },
 { from: "post", to: "status" },
 { from: "status", to: "patch" },
 { from: "patch", to: "table" },
 ],
 },
 images: [
 { src: "assets/screen-projek-form.png", label: "Form Tambah Projek" },
 { src: "assets/screen-projek-data.png", label: "Tabel Data Projek" },
 ],
 imageCaption: "Gambar 3.3–3.5: Form tambah dan tabel data projek kerja",
 },
 {
 id: 12,
 title: "Implementasi Modul 3: Manajemen Karyawan",
 subtitle: "Flowchart Alur & Tampilan Kelola Karyawan",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul manajemen karyawan untuk pendataan identitas, divisi, role, dan dokumen pendukung dengan fitur tambah, lihat detail, edit, dan hapus.",
 flowchart: "assets/flow-mod-karyawan.png",
 flowchartCaption: "Flowchart alur modul Manajemen Karyawan",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka KaryawanPage", r: 0, c: 1 },
 { id: "get", type: "io", text: "GET /karyawan → tampil tabel", r: 1, c: 1 },
 { id: "form", type: "process", text: "Form Tambah / Edit", r: 2, c: 1 },
 { id: "valid", type: "decision", text: "Validasi Laravel?", r: 3, c: 1 },
 { id: "err", type: "process", text: "Response error validasi", r: 4, c: 2 },
 { id: "ok", type: "io", text: "POST / PUT /karyawan", r: 4, c: 1 },
 { id: "save", type: "process", text: "Simpan DB + upload dokumen", r: 5, c: 1 },
 { id: "done", type: "end", text: "Data karyawan tersimpan", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "get" },
 { from: "get", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "ok", label: "Lolos" },
 { from: "valid", to: "err", label: "Gagal" },
 { from: "err", to: "form", lane: "right" },
 { from: "ok", to: "save" },
 { from: "save", to: "done" },
 ],
 },
 images: [
 { src: "assets/screen-karyawan-list.png", label: "Halaman Kelola Karyawan" },
 { src: "assets/screen-karyawan-form.png", label: "Form Tambah Karyawan" },
 ],
 imageCaption: "Gambar 3.6–3.8: Kelola karyawan dan form tambah karyawan",
 },
 {
 id: 13,
 title: "Implementasi Modul 4: Manajemen Inventory",
 subtitle: "Flowchart Alur & Tampilan Pendataan Aset",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul inventory memfasilitasi pendataan aset per divisi meliputi kode barang, stok, lokasi, kategori, dan foto. Validasi di BarangController, penyimpanan via POST /barang.",
 flowchart: "assets/flow-mod-inventory.png",
 flowchartCaption: "Flowchart alur modul Inventory Aset",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka InventoryPage", r: 0, c: 1 },
 { id: "get", type: "io", text: "GET /barang", r: 1, c: 1 },
 { id: "form", type: "process", text: "Form Tambah Barang (kode, stok, lokasi, kategori)", r: 2, c: 1 },
 { id: "valid", type: "decision", text: "Stok & kode valid?", r: 3, c: 1 },
 { id: "err", type: "process", text: "Tampilkan pesan error", r: 4, c: 2 },
 { id: "upload", type: "process", text: "Upload foto aset", r: 4, c: 1 },
 { id: "post", type: "io", text: "POST /barang", r: 5, c: 1 },
 { id: "save", type: "end", text: "Simpan ke MySQL", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "get" },
 { from: "get", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "upload", label: "Valid" },
 { from: "valid", to: "err", label: "Tidak" },
 { from: "err", to: "form", lane: "right" },
 { from: "upload", to: "post" },
 { from: "post", to: "save" },
 ],
 },
 images: [
 { src: "assets/screen-inventory-list.png", label: "Daftar Inventory" },
 { src: "assets/screen-inventory-form.png", label: "Form Tambah Barang" },
 ],
 imageCaption: "Gambar 3.9–3.11: Daftar dan form inventory aset",
 },
 {
 id: 14,
 title: "Implementasi Modul 5: Pengajuan & Approval Cuti",
 subtitle: "Flowchart Alur & Tampilan Halaman Cuti",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul cuti mendigitalisasi alur pengajuan oleh Admin dan approval Super Admin. Status: pending → approved atau rejected dengan alasan penolakan.",
 flowchart: "assets/flow-mod-cuti.png",
 flowchartCaption: "Flowchart alur modul Pengajuan & Approval Cuti",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Admin: Pengajuan Cuti", r: 0, c: 1 },
 { id: "post", type: "io", text: "POST /cuti → status: pending", r: 1, c: 1 },
 { id: "review", type: "decision", text: "Keputusan Super Admin?", r: 2, c: 1 },
 { id: "approve", type: "process", text: "Status: approved", r: 3, c: 0 },
 { id: "reject", type: "process", text: "Status: rejected (+ alasan)", r: 3, c: 2 },
 { id: "notif", type: "process", text: "Update status & notifikasi Admin", r: 4, c: 1 },
 { id: "done", type: "end", text: "Selesai", r: 5, c: 1 },
 ],
 edges: [
 { from: "start", to: "post" },
 { from: "post", to: "review" },
 { from: "review", to: "approve", label: "Setujui" },
 { from: "review", to: "reject", label: "Tolak" },
 { from: "approve", to: "notif" },
 { from: "reject", to: "notif" },
 { from: "notif", to: "done" },
 ],
 },
 images: [
 { src: "assets/screen-cuti-pengajuan.png", label: "Halaman Pengajuan Cuti" },
 { src: "assets/screen-cuti-approval.png", label: "Halaman Approval Cuti" },
 ],
 imageCaption: "Gambar 3.12–3.14: Halaman pengajuan dan approval cuti",
 },
 {
 id: 15,
 title: "Kendala dan Solusi",
 subtitle: "Tantangan Pengembangan dan Strategi Penanganannya",
 category: "evaluasi",
 categoryLabel: "Kendala & Solusi",
 notes:
 "Selama pengembangan ditemukan kendala utama yang diatasi melalui perencanaan bertahap, pendekatan iteratif, dan pengujian berkala antara frontend dan backend.",
 points: [
 { title: "Kendala: keterbatasan waktu", desc: "Pengembangan sistem berjalan paralel dengan penyusunan laporan magang.", type: "problem" },
 { title: "Solusi: perencanaan bertahap", desc: "Membagi fokus kerja antara pengerjaan sistem dan penulisan laporan per minggu.", type: "solution" },
 { title: "Kendala: perubahan kebutuhan", desc: "Requirement dari pengguna berubah secara bertahap selama implementasi.", type: "problem" },
 { title: "Solusi: pengembangan iteratif", desc: "Sistem dikembangkan fleksibel agar perubahan kebutuhan dapat diakomodasi.", type: "solution" },
 ],
 },
 {
 id: 16,
 title: "Simpulan dan Saran",
 subtitle: "Rangkuman Hasil Akhir & Rekomendasi Pengembangan Lanjutan",
 category: "penutup",
 categoryLabel: "Penutup",
 notes:
 "MANSYS berhasil menjawab permasalahan monitoring pekerjaan dan inventaris. Disarankan penambahan notifikasi otomatis, modul analitik, peningkatan keamanan, dan optimasi mobile.",
 points: [
 { title: "Simpulan", desc: "MANSYS berhasil mengintegrasikan monitoring pekerjaan dan inventaris aset dalam satu platform terpusat." },
 { title: "Capaian teknis", desc: "Seluruh modul inti diimplementasikan dan lulus pengujian fungsional sesuai kebutuhan operasional." },
 { title: "Saran: notifikasi & analitik", desc: "Tambahkan notifikasi real-time dan modul pelaporan untuk mendukung keputusan manajemen." },
 { title: "Saran: keamanan & mobile", desc: "Tingkatkan keamanan, backup berkala, regression testing, dan optimasi akses mobile." },
 ],
 },
 {
 id: 17,
 title: "Terima Kasih",
 subtitle: "Sesi Tanya Jawab - Penutup Presentasi Laporan Magang",
 category: "penutup",
 categoryLabel: "Terima Kasih",
 notes:
 "Presentasi telah selesai. Terima kasih atas perhatian Bapak/Ibu penguji dan dosen pembimbing. Saya siap membuka sesi tanya jawab seputar pengembangan MANSYS.",
 thankYou: true,
 },
];
