const PRESENTATION_META = {
 student: "Atila Fazrul Falah",
 nim: "00000111118",
 totalSlides: 21,
};

const SLIDES = [
 {
 id: 1,
 title: "Latar Belakang Masalah",
 subtitle: "Kebutuhan Sistem Terintegrasi untuk Monitoring Pekerjaan & Inventaris Aset",
 category: "pembuka",
 categoryLabel: "Pendahuluan",
 notes:
 "Selamat pagi/siang Bapak/Ibu penguji dan Bapak/Ibu dosen pembimbing. Pada slide ini saya memaparkan latar belakang masalah di PT. Hayati Semesta Raharja. Seiring bertambahnya volume pekerjaan dan aset operasional, proses monitoring dan inventaris yang masih manual berpotensi menimbulkan kesalahan pencatatan serta keterlambatan informasi antar divisi.",
 points: [
 { title: "Kondisi awal di perusahaan", desc: "PT. HSR masih mengandalkan pencatatan manual atau semi-digital untuk monitoring pekerjaan dan inventaris aset." },
 { title: "Dampak operasional", desc: "Berpotensi menimbulkan kesalahan pencatatan, keterlambatan informasi, dan kesulitan pengawasan lintas divisi." },
 { title: "Kebutuhan solusi", desc: "Dibutuhkan sistem berbasis web yang mengintegrasikan monitoring pekerjaan dan pengelolaan inventaris dalam satu platform." },
 { title: "Solusi yang dikembangkan", desc: "MANSYS (Management System) dirancang sebagai platform terpusat untuk menjawab kebutuhan tersebut." },
 ],
 },
 {
 id: 2,
 title: "Maksud dan Tujuan Kerja Magang",
 subtitle: "Pemenuhan Akademik & Pengembangan Sistem Digital Operasional",
 category: "profil",
 categoryLabel: "Pendahuluan",
 notes:
 "Magang dilaksanakan sebagai pemenuhan kewajiban akademik sekaligus pengalaman kerja profesional. Tujuan utamanya adalah merancang dan membangun MANSYS agar operasional perusahaan lebih efisien dan terintegrasi.",
 points: [
 { title: "Maksud dan tujuan magang", desc: "Memenuhi kewajiban akademik, menerapkan ilmu perkuliahan ke lingkungan kerja nyata, serta mengembangkan sistem digital operasional di PT. HSR." },
 { title: "Tujuan utama", desc: "Merancang dan mengembangkan sistem monitoring pekerjaan serta inventaris aset yang terpusat di PT. HSR." },
 { title: "Target hasil", desc: "Operasional lebih efektif, transparan, dan minim risiko kesalahan pencatatan data." },
 ],
 },
 {
 id: 3,
 title: "Sejarah Singkat Perusahaan",
 subtitle: "Visi, Misi, dan Profil PT. Hayati Semesta Raharja",
 category: "profil",
 categoryLabel: "Gambaran Umum Perusahaan",
 companyProfile: true,
 logo: "assets/logos/logo-hsr.png",
 notes:
 "PT. Hayati Semesta Raharja adalah perusahaan nasional di sektor kesehatan. Persiapan usaha dimulai sejak 2017 dan resmi berbadan hukum pada 2021 di Tangerang, Banten. Perusahaan bergerak di perdagangan alat medis, farmasi, laboratorium, radiologi, serta layanan servis perangkat kesehatan.",
 points: [
 { title: "Profil perusahaan", desc: "PT. HSR dirintis 2017, resmi berdiri 2021. Dipimpin Direktur Utama Syahrul Roji. Kantor pusat di Sukaasih, Tangerang, Banten." },
 { title: "Ruang lingkup bisnis", desc: "Distribusi alat kesehatan, BHP, servis hardware/software perangkat medis, software penunjang medis, dan konstruksi ruang medis." },
 { title: "Visi", desc: "Menjadi perusahaan yang bermanfaat dalam perkembangan fasilitas kesehatan di Indonesia." },
 { title: "Misi", desc: "Membangun perusahaan yang berdedikasi dan terdepan dalam perkembangan industri kesehatan Indonesia." },
 ],
 },
 {
 id: 5,
 title: "Uraian Sistem MANSYS",
 subtitle: "Gambaran Umum, Tahapan Pengembangan, dan Tech Stack",
 category: "fitur",
 categoryLabel: "Pelaksanaan Kerja Magang",
 notes:
 "Pada bagian ini saya menjelaskan inti dari pekerjaan saya selama magang, yaitu membangun MANSYS untuk menggantikan proses administrasi manual perusahaan. Saya mulai dengan menggali kebutuhan tiap divisi melalui diskusi, baru kemudian merancang basis data dan endpoint API-nya, lalu menghubungkan tampilan dengan server. Untuk teknologinya saya memakai React di sisi tampilan, Laravel 12 untuk logika dan API, serta MySQL sebagai penyimpanan datanya.",
 narrative: [
 "Fokus utama dalam pelaksanaan magang ini adalah merancang dan mengembangkan \"MANSYS\". MANSYS merupakan sebuah sistem manajemen internal berbasis web yang dibangun untuk memperbarui sistem administrasi konvensional perusahaan menjadi sebuah sistem digital yang terintegrasi secara penuh.",
 ],
 sections: [
 {
 heading: "Tahapan Pengembangan",
 items: [
 "Identifikasi kebutuhan operasional perusahaan.",
 "Menyusun arsitektur basis data, API endpoint, serta perancangan antarmuka.",
 "Integrasikannya frontend dan backend melalui RESTful API.",
 ],
 },
 {
 heading: "Tech Stack",
 items: [
 "React.js (Frontend)",
 "Laravel 12 (Backend)",
 "MySQL (Database)",
 ],
 },
 ],
 },
 {
 id: 6,
 title: "Use Case Diagram MANSYS",
 subtitle: "Interaksi Aktor Divisi dengan Modul Utama Sistem",
 category: "fitur",
 categoryLabel: "Gambaran Sistem",
 notes:
 "Use case diagram menggambarkan interaksi Sales, Service, dan Purchasing dengan modul penjualan, projek kerja, inventory, dan pembelian. Sales mengelola transaksi penjualan dan inisiasi projek. Service mengelola inventaris dan melaksanakan projek. Purchasing mengurus pengadaan barang. Super Admin memiliki akses penuh ke seluruh fitur.",
 flowchart: true,
 flowchartFull: true,
 usecase: true,
 image: "assets/flow-usecase-mansys.png",
 imageCaption: "Use case diagram MANSYS — interaksi aktor divisi dengan modul utama",
 intro: "Sistem ini melibatkan 3 aktor utama, yaitu:",
 outro: "Selain itu terdapat Super Admin yang mendapatkan akses penuh atas semua fitur yang ada.",
 points: [
 { title: "Sales", desc: "Berfokus pada manajemen transaksi penjualan dan inisiasi proyek kerja." },
 { title: "Service", desc: "Berfokus pada pengelolaan inventaris operasional dan pelaksanaan proyek kerja." },
 { title: "Purchasing", desc: "Berfokus pada pengadaan barang dan manajemen pembelian." },
 ],
 },
 {
 id: 7,
 title: "5 Modul yang Diimplementasikan",
 subtitle: "Dashboard, Projek Kerja, Karyawan, Inventory, dan Cuti Karyawan",
 category: "fitur",
 categoryLabel: "Implementasi Fitur",
 notes:
 "Selama 15 minggu pengembangan, penulis mengimplementasikan 5 modul utama. Slide berikutnya menampilkan flowchart alur kerja dan screenshot implementasi tiap modul.",
 points: [
 { title: "1. Dashboard Super Admin & Admin", desc: "Halaman utama setelah login, ringkasan pekerjaan per divisi sesuai role." },
 { title: "2. Modul Projek Kerja", desc: "CRUD projek, status pekerjaan, invite user, upload dokumentasi foto/file." },
 { title: "3. Modul Manajemen Karyawan", desc: "Pendataan identitas, divisi, role, dan dokumen pendukung karyawan." },
 { title: "4. Modul Manajemen Inventory", desc: "Pendataan aset per divisi: kode barang, stok, lokasi, kategori, foto." },
 { title: "5. Modul Pengajuan & Approval Cuti", desc: "Pengajuan cuti Admin dan approval Super Admin (pending/approved/rejected)." },
 ],
 },
 {
 id: 8,
 title: "Implementasi Modul 1: Dashboard",
 subtitle: "Tampilan Dashboard, Status Summary, Biaya Non-Projek, dan Work Activity",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul dashboard menampilkan card per divisi beserta jumlah pekerjaan, status summary keseluruhan tugas, pencatatan biaya non-projek, dan tabel work activity. Super Admin melihat seluruh divisi, Admin hanya divisi masing-masing. Data diambil via GET /projek-kerja dengan filter role. Flowchart alur lengkap modul ini dapat dilihat pada bagian Lampiran.",
 desc: [
 "Setelah login, pengguna disambut halaman utama yang menampilkan card per divisi (IT, Service, Sales, Kontraktor, Logistik, Purchasing) lengkap dengan jumlah tugas pada masing-masing divisi.",
 "Tampilan menyesuaikan hak akses: Super Admin melihat seluruh divisi, sedangkan Admin hanya divisinya sendiri. Data diambil langsung dari REST API lalu dihitung untuk tiap divisi.",
 "Terdapat status summary yang merangkum seluruh tugas berdasarkan statusnya (Created, Preparation, Work in Progress, Editing, Invoicing, Completed) beserta pencatatan biaya non-projek (travel, expense, reimbursement).",
 "Tabel work activity menampilkan daftar pekerjaan dengan filter divisi/status serta detail tugas, karyawan, lokasi, tanggal, dan status pengerjaan.",
 ],
 images: [
 { src: "assets/screen-dashboard-sa.png", label: "Dashboard Super Admin" },
 { src: "assets/screen-dashboard-admin.png", label: "Dashboard Admin" },
 { src: "assets/screen-dashboard-status.png", label: "Status Summary & Non-Project Costs" },
 { src: "assets/screen-dashboard-activity.png", label: "Tabel Work Activity" },
 ],
 imageCaption: "Gambar 3.1–3.4: Tampilan dashboard, status summary, dan work activity",
 },
 {
 id: 9,
 title: "Implementasi Modul 2: Projek Kerja",
 subtitle: "Flowchart Alur & Tampilan Form dan Tabel Projek",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul projek kerja mendukung penambahan projek, pengisian divisi, karyawan, lokasi, status, upload dokumentasi, serta tabel data dengan pencarian dan aksi CRUD. Flowchart alur lengkap modul ini dapat dilihat pada bagian Lampiran.",
 desc: [
 "Terdapat halaman formulir untuk memasukkan detail data proyek dan mengunggah foto/file dokumentasi, serta halaman daftar proyek berupa tabel interaktif untuk memantau status pengerjaan secara langsung (Persiapan, Proses, Selesai).",
 "Selain itu juga terdapat divisi yang terlibat dalam masing-masing projek kerja.",
 ],
 images: [
 { src: "assets/screen-projek-form.png", label: "Form Tambah Projek" },
 { src: "assets/screen-projek-data.png", label: "Tabel Data Projek" },
 ],
 imageCaption: "Gambar 3.3–3.5: Form tambah dan tabel data projek kerja",
 },
 {
 id: 10,
 title: "Implementasi Modul 3: Manajemen Karyawan",
 subtitle: "Flowchart Alur & Tampilan Kelola Karyawan",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul manajemen karyawan untuk pendataan identitas, divisi, role, dan dokumen pendukung dengan fitur tambah, lihat detail, edit, dan hapus. Flowchart alur lengkap modul ini dapat dilihat pada bagian Lampiran.",
 desc: [
 "Terdapat halaman untuk mengelola data karyawan yang mencakup identitas, divisi, role, serta dokumen pendukung setiap karyawan.",
 "Pengguna dapat menambah, melihat detail, mengubah, dan menghapus data, di mana seluruh masukan divalidasi terlebih dahulu di sisi server sebelum disimpan.",
 ],
 images: [
 { src: "assets/screen-karyawan-list.png", label: "Halaman Kelola Karyawan" },
 { src: "assets/screen-karyawan-form.png", label: "Form Tambah Karyawan" },
 ],
 imageCaption: "Gambar 3.6–3.8: Kelola karyawan dan form tambah karyawan",
 },
 {
 id: 11,
 title: "Implementasi Modul 4: Manajemen Inventory",
 subtitle: "Flowchart Alur & Tampilan Pendataan Aset",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul inventory memfasilitasi pendataan aset per divisi meliputi kode barang, stok, lokasi, kategori, dan foto. Validasi di BarangController, penyimpanan via POST /barang. Flowchart alur lengkap modul ini dapat dilihat pada bagian Lampiran.",
 desc: [
 "Terdapat halaman untuk mendata aset/inventaris setiap divisi yang meliputi kode barang, jumlah stok, lokasi, kategori, dan foto barang.",
 "Setiap penambahan barang divalidasi terlebih dahulu (stok dan kode) sebelum data tersimpan ke dalam basis data.",
 ],
 images: [
 { src: "assets/screen-inventory-list.png", label: "Daftar Inventory" },
 { src: "assets/screen-inventory-form.png", label: "Form Tambah Barang" },
 ],
 imageCaption: "Gambar 3.9–3.11: Daftar dan form inventory aset",
 },
 {
 id: 12,
 title: "Implementasi Modul 5: Pengajuan & Approval Cuti",
 subtitle: "Flowchart Alur & Tampilan Halaman Cuti",
 category: "demo",
 categoryLabel: "Implementasi Visual",
 moduleImpl: true,
 notes:
 "Modul cuti mendigitalisasi alur pengajuan oleh Admin dan approval Super Admin. Status: pending → approved atau rejected dengan alasan penolakan. Flowchart alur lengkap modul ini dapat dilihat pada bagian Lampiran.",
 desc: [
 "Terdapat halaman pengajuan cuti yang dapat diisi oleh Admin, serta halaman persetujuan yang dikelola oleh Super Admin.",
 "Status pengajuan berjalan dari pending menjadi disetujui atau ditolak (disertai alasan penolakan), kemudian Admin menerima pemberitahuan atas keputusan tersebut.",
 ],
 images: [
 { src: "assets/screen-cuti-pengajuan.png", label: "Halaman Pengajuan Cuti" },
 { src: "assets/screen-cuti-approval.png", label: "Halaman Approval Cuti" },
 ],
 imageCaption: "Gambar 3.12–3.14: Halaman pengajuan dan approval cuti",
 },
 {
 id: 13,
 title: "Kendala dan Solusi",
 subtitle: "Tantangan Pengembangan dan Strategi Penanganannya",
 category: "evaluasi",
 categoryLabel: "Kendala & Solusi",
 notes:
 "Selama pengembangan ditemukan kendala utama yang diatasi melalui perencanaan bertahap, pendekatan iteratif, dan pengujian berkala antara frontend dan backend.",
 points: [
 { title: "Kendala: keterbatasan waktu", desc: "Pengembangan sistem berjalan paralel dengan penyusunan laporan magang.", type: "problem" },
 { title: "Solusi: perencanaan bertahap", desc: "Membagi fokus kerja antara pengerjaan sistem dan penulisan laporan per minggu.", type: "solution" },
 { title: "Kendala: perubahan kebutuhan", desc: "Requirement dari pengguna berubah secara bertahap selama implementasi.", type: "problem" },
 { title: "Solusi: pengembangan iteratif", desc: "Sistem dikembangkan fleksibel agar perubahan kebutuhan dapat diakomodasi.", type: "solution" },
 ],
 },
 {
 id: 14,
 title: "Simpulan dan Saran",
 subtitle: "Rangkuman Hasil Akhir & Rekomendasi Pengembangan Lanjutan",
 category: "penutup",
 categoryLabel: "Penutup",
 notes:
 "Simpulan disusun untuk menjawab maksud dan tujuan kerja magang. Tujuan utama merancang dan mengembangkan sistem monitoring pekerjaan serta inventaris aset yang terpusat telah tercapai melalui MANSYS. Target hasil berupa operasional yang lebih efektif, transparan, dan minim kesalahan pencatatan juga terpenuhi, sekaligus menjawab maksud akademik yaitu penerapan ilmu perkuliahan pada lingkungan kerja nyata. Disarankan penambahan notifikasi otomatis, modul analitik, peningkatan keamanan, dan optimasi mobile.",
 points: [
 { title: "Tujuan utama tercapai", desc: "Sistem monitoring pekerjaan dan inventaris aset yang terpusat berhasil dirancang dan dikembangkan dalam satu platform, yaitu MANSYS." },
 { title: "Target hasil terpenuhi", desc: "Operasional menjadi lebih efektif, transparan, dan minim risiko kesalahan pencatatan; seluruh modul inti diimplementasikan dan lulus pengujian fungsional." },
 { title: "Maksud akademik tercapai", desc: "Ilmu perkuliahan diterapkan langsung pada lingkungan kerja nyata melalui perancangan basis data, REST API, dan antarmuka sistem di PT. HSR." },
 { title: "Saran pengembangan", desc: "Tambahkan notifikasi real-time & modul analitik, serta tingkatkan keamanan, backup berkala, dan optimasi akses mobile." },
 ],
 },
 {
 id: 15,
 title: "Terima Kasih",
 subtitle: "Sesi Tanya Jawab - Penutup Presentasi Laporan Magang",
 category: "penutup",
 categoryLabel: "Terima Kasih",
 notes:
 "Presentasi telah selesai. Terima kasih atas perhatian Bapak/Ibu penguji dan dosen pembimbing. Saya siap membuka sesi tanya jawab seputar pengembangan MANSYS.",
 thankYou: true,
 },
 {
 id: 16,
 title: "Flowchart Autentikasi & Role-Based Access",
 subtitle: "Alur Login, Laravel Sanctum, dan Routing Berdasarkan Role",
 category: "fitur",
 categoryLabel: "Lampiran · Flowchart Sistem",
 notes:
 "Flowchart autentikasi: pengguna login via POST /api/login, token Sanctum disimpan, lalu diarahkan ke dashboard sesuai role super_admin, admin, atau user. Sistem memantau idle 15 menit dan session timeout.",
 flowchart: true,
 flowchartFull: true,
 image: "assets/flow-auth-role.png",
 imageCaption: "Flowchart autentikasi & role-based access (idle 15 menit memicu session timeout → login ulang)",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Mulai", r: 0, c: 1 },
 { id: "open", type: "process", text: "Buka Aplikasi MANSYS", r: 1, c: 1 },
 { id: "token", type: "decision", text: "Token Sanctum valid?", r: 2, c: 1 },
 { id: "login", type: "process", text: "Tampilkan halaman login", r: 3, c: 1 },
 { id: "post", type: "io", text: "Input kredensial → POST /api/login", r: 4, c: 1 },
 { id: "loginok", type: "decision", text: "Login berhasil?", r: 5, c: 1 },
 { id: "savetoken", type: "process", text: "Simpan token Sanctum", r: 6, c: 1 },
 { id: "role", type: "decision", text: "Cek user.role", r: 7, c: 1 },
 { id: "sa", type: "process", text: "Route /super-admin/*", r: 8, c: 0 },
 { id: "adm", type: "process", text: "Route /admin/*", r: 8, c: 1 },
 { id: "usr", type: "process", text: "Route /user/*", r: 8, c: 2 },
 { id: "dash", type: "end", text: "Dashboard sesuai role", r: 9, c: 1 },
 ],
 edges: [
 { from: "start", to: "open" },
 { from: "open", to: "token" },
 { from: "token", to: "login", label: "Tidak" },
 { from: "token", to: "role", label: "Ya", lane: "right" },
 { from: "login", to: "post" },
 { from: "post", to: "loginok" },
 { from: "loginok", to: "login", label: "Tidak", lane: "left" },
 { from: "loginok", to: "savetoken", label: "Ya" },
 { from: "savetoken", to: "role" },
 { from: "role", to: "sa", label: "super_admin" },
 { from: "role", to: "adm", label: "admin" },
 { from: "role", to: "usr", label: "user" },
 { from: "sa", to: "dash" },
 { from: "adm", to: "dash" },
 { from: "usr", to: "dash" },
 ],
 },
 },
 {
 id: 17,
 title: "Flowchart Navigasi Modul MANSYS",
 subtitle: "Sidebar, Division Hub, dan Integrasi REST API",
 category: "fitur",
 categoryLabel: "Lampiran · Flowchart Sistem",
 notes:
 "Setelah login, pengguna mengakses modul global via sidebar atau modul divisi via division hub. Semua halaman React.js terhubung ke REST API Laravel.",
 flowchart: true,
 flowchartFull: true,
 image: "assets/flow-module-nav.png",
 imageCaption: "Flowchart navigasi modul MANSYS",
 flow: {
 cols: 3,
 nodes: [
 { id: "dash", type: "start", text: "Dashboard (setelah login)", r: 0, c: 1 },
 { id: "pick", type: "decision", text: "Pilih jenis menu?", r: 1, c: 1 },
 { id: "gnav", type: "process", text: "Sidebar — Menu Global", r: 2, c: 0 },
 { id: "dnav", type: "process", text: "Division Hub — pilih divisi", r: 2, c: 2 },
 { id: "gpage", type: "process", text: "Karyawan, Cuti, Rekap Biaya, Berita Acara", r: 3, c: 0 },
 { id: "dpage", type: "process", text: "Projek, Inventory, Pembelian, Target, Daily Report", r: 3, c: 2 },
 { id: "react", type: "process", text: "Halaman React.js (komponen page)", r: 4, c: 1 },
 { id: "api", type: "io", text: "Request REST API Laravel (token Sanctum)", r: 5, c: 1 },
 { id: "render", type: "end", text: "Render data sesuai hak akses", r: 6, c: 1 },
 ],
 edges: [
 { from: "dash", to: "pick" },
 { from: "pick", to: "gnav", label: "Modul Global" },
 { from: "pick", to: "dnav", label: "Modul Divisi" },
 { from: "gnav", to: "gpage" },
 { from: "dnav", to: "dpage" },
 { from: "gpage", to: "react" },
 { from: "dpage", to: "react" },
 { from: "react", to: "api" },
 { from: "api", to: "render" },
 ],
 },
 },
 {
 id: 18,
 title: "Lampiran — Flowchart Modul (1/2)",
 subtitle: "Flowchart Alur Dashboard, Projek Kerja, dan Manajemen Karyawan",
 category: "fitur",
 categoryLabel: "Lampiran · Flowchart Modul",
 flowchartFull: true,
 notes:
 "Halaman lampiran ini menampilkan flowchart alur kerja tiga modul: Dashboard (login → cek role → GET /projek-kerja → render DivisiCard), Projek Kerja (input → validasi → upload → POST → pembaruan status), dan Manajemen Karyawan (GET /karyawan → form → validasi Laravel → simpan).",
 imageCaption: "Flowchart alur modul Dashboard, Projek Kerja, dan Manajemen Karyawan.",
 flowGallery: [
 {
 label: "Modul 1 — Dashboard",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Mulai", r: 0, c: 1 },
 { id: "login", type: "process", text: "Login (token Sanctum)", r: 1, c: 1 },
 { id: "role", type: "decision", text: "Cek role user?", r: 2, c: 1 },
 { id: "sa", type: "process", text: "Super Admin: semua divisi", r: 3, c: 0 },
 { id: "adm", type: "process", text: "Admin: divisi sendiri", r: 3, c: 1 },
 { id: "usr", type: "process", text: "User: projek di-invite", r: 3, c: 2 },
 { id: "get", type: "io", text: "GET /projek-kerja (filter role)", r: 4, c: 1 },
 { id: "count", type: "process", text: "Hitung jumlah pekerjaan / divisi", r: 5, c: 1 },
 { id: "render", type: "end", text: "Render DivisiCard", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "login" },
 { from: "login", to: "role" },
 { from: "role", to: "sa", label: "super_admin" },
 { from: "role", to: "adm", label: "admin" },
 { from: "role", to: "usr", label: "user" },
 { from: "sa", to: "get" },
 { from: "adm", to: "get" },
 { from: "usr", to: "get" },
 { from: "get", to: "count" },
 { from: "count", to: "render" },
 ],
 },
 },
 {
 label: "Modul 2 — Projek Kerja",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka Projek Kerja", r: 0, c: 1 },
 { id: "form", type: "process", text: "Form Tambah Projek (divisi, lokasi, karyawan)", r: 1, c: 1 },
 { id: "valid", type: "decision", text: "Input valid?", r: 2, c: 1 },
 { id: "err", type: "process", text: "Tampilkan pesan error", r: 3, c: 2 },
 { id: "upload", type: "process", text: "Upload foto & dokumen", r: 3, c: 1 },
 { id: "post", type: "io", text: "POST /projek-kerja", r: 4, c: 1 },
 { id: "status", type: "process", text: "Set status awal: Dibuat", r: 5, c: 1 },
 { id: "patch", type: "io", text: "PATCH status: Persiapan → Proses → Editing → Invoicing → Selesai", r: 6, c: 1 },
 { id: "table", type: "end", text: "Tampil tabel data projek", r: 7, c: 1 },
 ],
 edges: [
 { from: "start", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "upload", label: "Ya" },
 { from: "valid", to: "err", label: "Tidak" },
 { from: "err", to: "form", lane: "right" },
 { from: "upload", to: "post" },
 { from: "post", to: "status" },
 { from: "status", to: "patch" },
 { from: "patch", to: "table" },
 ],
 },
 },
 {
 label: "Modul 3 — Manajemen Karyawan",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka KaryawanPage", r: 0, c: 1 },
 { id: "get", type: "io", text: "GET /karyawan → tampil tabel", r: 1, c: 1 },
 { id: "form", type: "process", text: "Form Tambah / Edit", r: 2, c: 1 },
 { id: "valid", type: "decision", text: "Validasi Laravel?", r: 3, c: 1 },
 { id: "err", type: "process", text: "Response error validasi", r: 4, c: 2 },
 { id: "ok", type: "io", text: "POST / PUT /karyawan", r: 4, c: 1 },
 { id: "save", type: "process", text: "Simpan DB + upload dokumen", r: 5, c: 1 },
 { id: "done", type: "end", text: "Data karyawan tersimpan", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "get" },
 { from: "get", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "ok", label: "Lolos" },
 { from: "valid", to: "err", label: "Gagal" },
 { from: "err", to: "form", lane: "right" },
 { from: "ok", to: "save" },
 { from: "save", to: "done" },
 ],
 },
 },
 ],
 },
 {
 id: 19,
 title: "Lampiran — Flowchart Modul (2/2)",
 subtitle: "Flowchart Alur Manajemen Inventory dan Pengajuan & Approval Cuti",
 category: "fitur",
 categoryLabel: "Lampiran · Flowchart Modul",
 flowchartFull: true,
 notes:
 "Halaman lampiran ini menampilkan flowchart alur kerja dua modul: Manajemen Inventory (GET /barang → form aset → validasi stok & kode → upload foto → POST /barang) dan Pengajuan & Approval Cuti (Admin ajukan → keputusan Super Admin → approved/rejected → notifikasi).",
 imageCaption: "Flowchart alur modul Manajemen Inventory dan Pengajuan & Approval Cuti.",
 flowGallery: [
 {
 label: "Modul 4 — Manajemen Inventory",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Buka InventoryPage", r: 0, c: 1 },
 { id: "get", type: "io", text: "GET /barang", r: 1, c: 1 },
 { id: "form", type: "process", text: "Form Tambah Barang (kode, stok, lokasi, kategori)", r: 2, c: 1 },
 { id: "valid", type: "decision", text: "Stok & kode valid?", r: 3, c: 1 },
 { id: "err", type: "process", text: "Tampilkan pesan error", r: 4, c: 2 },
 { id: "upload", type: "process", text: "Upload foto aset", r: 4, c: 1 },
 { id: "post", type: "io", text: "POST /barang", r: 5, c: 1 },
 { id: "save", type: "end", text: "Simpan ke MySQL", r: 6, c: 1 },
 ],
 edges: [
 { from: "start", to: "get" },
 { from: "get", to: "form" },
 { from: "form", to: "valid" },
 { from: "valid", to: "upload", label: "Valid" },
 { from: "valid", to: "err", label: "Tidak" },
 { from: "err", to: "form", lane: "right" },
 { from: "upload", to: "post" },
 { from: "post", to: "save" },
 ],
 },
 },
 {
 label: "Modul 5 — Pengajuan & Approval Cuti",
 flow: {
 cols: 3,
 nodes: [
 { id: "start", type: "start", text: "Admin: Pengajuan Cuti", r: 0, c: 1 },
 { id: "post", type: "io", text: "POST /cuti → status: pending", r: 1, c: 1 },
 { id: "review", type: "decision", text: "Keputusan Super Admin?", r: 2, c: 1 },
 { id: "approve", type: "process", text: "Status: approved", r: 3, c: 0 },
 { id: "reject", type: "process", text: "Status: rejected (+ alasan)", r: 3, c: 2 },
 { id: "notif", type: "process", text: "Update status & notifikasi Admin", r: 4, c: 1 },
 { id: "done", type: "end", text: "Selesai", r: 5, c: 1 },
 ],
 edges: [
 { from: "start", to: "post" },
 { from: "post", to: "review" },
 { from: "review", to: "approve", label: "Setujui" },
 { from: "review", to: "reject", label: "Tolak" },
 { from: "approve", to: "notif" },
 { from: "reject", to: "notif" },
 { from: "notif", to: "done" },
 ],
 },
 },
 ],
 },
 {
 id: 20,
 title: "Lampiran — Endpoint API (1/3)",
 subtitle: "Modul Dashboard dan Modul Manajemen Karyawan",
 category: "fitur",
 categoryLabel: "Lampiran · Endpoint API",
 flowchartFull: true,
 notes:
 "Daftar endpoint REST API berdasarkan implementasi di routes/api.php pada repository web-HSR. Modul Dashboard menggunakan endpoint projek-kerja, dashboard-biaya, dan activity-logs. Modul Manajemen Karyawan menggunakan endpoint karyawan.",
 endpoints: true,
 tables: [
 {
 title: "Endpoint Modul Dashboard",
 rows: [
 { method: "GET", path: "/projek-kerja", desc: "Mengambil seluruh pekerjaan untuk dihitung per divisi." },
 { method: "GET", path: "/dashboard-biaya", desc: "Mengambil daftar biaya di luar projek." },
 { method: "GET", path: "/dashboard-biaya/summary", desc: "Ringkasan total biaya non-projek." },
 { method: "POST", path: "/dashboard-biaya", desc: "Menambahkan catatan biaya non-projek." },
 { method: "PATCH", path: "/dashboard-biaya/{id}", desc: "Mengubah data biaya non-projek." },
 { method: "DELETE", path: "/dashboard-biaya/{id}", desc: "Menghapus catatan biaya non-projek." },
 { method: "GET", path: "/dashboard-biaya/export-kas", desc: "Mengunduh rekap kas." },
 { method: "GET", path: "/activity-logs", desc: "Menampilkan log aktivitas (Super Admin)." },
 ],
 },
 {
 title: "Endpoint Modul Manajemen Karyawan",
 rows: [
 { method: "GET", path: "/karyawan", desc: "Menampilkan seluruh data karyawan." },
 { method: "GET", path: "/karyawan/{id}", desc: "Menampilkan detail satu karyawan." },
 { method: "POST", path: "/karyawan", desc: "Menambahkan data karyawan baru." },
 { method: "PUT", path: "/karyawan/{id}", desc: "Mengupdate data karyawan." },
 { method: "DELETE", path: "/karyawan/{id}", desc: "Menghapus data karyawan." },
 { method: "POST", path: "/karyawan/{id}/delete-file", desc: "Menghapus salah satu dokumen karyawan." },
 { method: "GET", path: "/karyawan/{id}/ktp", desc: "Mengunduh / preview dokumen KTP." },
 { method: "GET", path: "/karyawan/{id}/ijazah", desc: "Mengunduh / preview dokumen ijazah." },
 ],
 },
 ],
 },
 {
 id: 21,
 title: "Lampiran — Endpoint API (2/3)",
 subtitle: "Modul Projek Kerja: Data, Status, Foto, dan Dokumen",
 category: "fitur",
 categoryLabel: "Lampiran · Endpoint API",
 flowchartFull: true,
 notes:
 "Endpoint modul Projek Kerja terbagi menjadi pengelolaan data & status projek serta pengelolaan foto dan dokumen projek, sesuai ProjekKerjaController pada web-HSR.",
 endpoints: true,
 tables: [
 {
 title: "Projek Kerja — Data & Status",
 rows: [
 { method: "GET", path: "/projek-kerja", desc: "Mengambil daftar semua projek kerja." },
 { method: "POST", path: "/projek-kerja", desc: "Menambahkan projek kerja baru." },
 { method: "GET", path: "/projek-kerja/{id}", desc: "Menampilkan detail satu projek." },
 { method: "PUT", path: "/projek-kerja/{id}", desc: "Mengupdate seluruh data projek." },
 { method: "PATCH", path: "/projek-kerja/{id}/status", desc: "Mengubah status projek kerja." },
 { method: "PATCH", path: "/projek-kerja/{id}/deskripsi", desc: "Mengubah deskripsi projek." },
 { method: "PATCH", path: "/projek-kerja/{id}/uang", desc: "Mengelola rincian biaya projek." },
 { method: "PATCH", path: "/projek-kerja/{id}/lunas", desc: "Mengubah status pelunasan." },
 { method: "GET", path: "/projek-kerja/{id}/export-biaya", desc: "Mengunduh rincian biaya (CSV)." },
 { method: "DELETE", path: "/projek-kerja/{id}", desc: "Menghapus data projek kerja." },
 ],
 },
 {
 title: "Projek Kerja — Foto & Dokumen",
 rows: [
 { method: "GET", path: "/projek-kerja/{id}/photos", desc: "Mengambil daftar foto dokumentasi." },
 { method: "POST", path: "/projek-kerja/{id}/add-photo", desc: "Menambahkan foto dokumentasi." },
 { method: "DELETE", path: "/projek-kerja/photo/{id}", desc: "Menghapus satu foto dokumentasi." },
 { method: "GET", path: "/projek-kerja/{id}/files", desc: "Mengambil daftar dokumen projek." },
 { method: "POST", path: "/projek-kerja/{id}/add-file", desc: "Menambahkan dokumen projek." },
 { method: "DELETE", path: "/projek-kerja/file/{id}", desc: "Menghapus satu dokumen projek." },
 { method: "GET", path: "/projek-kerja/{id}/folders", desc: "Mengambil folder media projek." },
 { method: "POST", path: "/projek-kerja/{id}/folders", desc: "Membuat folder media baru." },
 ],
 },
 ],
 },
 {
 id: 22,
 title: "Lampiran — Endpoint API (3/3)",
 subtitle: "Modul Manajemen Inventory dan Modul Pengajuan & Approval Cuti",
 category: "fitur",
 categoryLabel: "Lampiran · Endpoint API",
 flowchartFull: true,
 notes:
 "Modul Inventory mencakup endpoint barang (servis) dan logistik-inventory. Modul Cuti mencakup pengajuan, persetujuan, dan penolakan sesuai CutiController pada web-HSR.",
 endpoints: true,
 tables: [
 {
 title: "Endpoint Modul Manajemen Inventory",
 rows: [
 { method: "GET", path: "/barang", desc: "Menampilkan seluruh inventori barang." },
 { method: "GET", path: "/barang/{id}", desc: "Menampilkan detail satu barang." },
 { method: "POST", path: "/barang", desc: "Menambahkan data barang baru." },
 { method: "PUT", path: "/barang/{id}", desc: "Mengupdate data barang & foto." },
 { method: "DELETE", path: "/barang/{id}", desc: "Menghapus barang secara permanen." },
 { method: "GET", path: "/logistik-inventory", desc: "Menampilkan seluruh barang logistik." },
 { method: "POST", path: "/logistik-inventory", desc: "Menambahkan barang logistik baru." },
 { method: "PUT", path: "/logistik-inventory/{id}", desc: "Mengupdate barang logistik." },
 { method: "DELETE", path: "/logistik-inventory/{id}", desc: "Menghapus barang logistik." },
 ],
 },
 {
 title: "Endpoint Modul Pengajuan & Approval Cuti",
 rows: [
 { method: "GET", path: "/cuti", desc: "Menampilkan daftar pengajuan cuti." },
 { method: "GET", path: "/cuti/summary", desc: "Ringkasan jumlah pending/approved/rejected." },
 { method: "GET", path: "/cuti/{id}", desc: "Menampilkan detail pengajuan cuti." },
 { method: "POST", path: "/cuti", desc: "Mengajukan cuti baru (multipart lampiran)." },
 { method: "PUT", path: "/cuti/{id}", desc: "Mengupdate data pengajuan cuti." },
 { method: "POST", path: "/cuti/{id}/approve", desc: "Super Admin menyetujui cuti." },
 { method: "POST", path: "/cuti/{id}/reject", desc: "Super Admin menolak (+ alasan)." },
 { method: "DELETE", path: "/cuti/{id}", desc: "Menghapus pengajuan cuti." },
 ],
 },
 ],
 },
];
